// <auto-generated />
using System;
using DemoFacturacionHacienda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoFacturacionHacienda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319192303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DemoFacturacionHacienda.Models.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmisorCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmisorNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeHacienda")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroConsecutivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptorCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptorCorreo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptorNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalComprobante")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalImpuesto")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalVenta")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("DemoFacturacionHacienda.Models.Entities.LineaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FacturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroLinea")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeIVA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("LineasDetalle");
                });

            modelBuilder.Entity("DemoFacturacionHacienda.Models.Entities.LineaDetalle", b =>
                {
                    b.HasOne("DemoFacturacionHacienda.Models.Entities.Factura", "Factura")
                        .WithMany("Lineas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("DemoFacturacionHacienda.Models.Entities.Factura", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
